apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: aks-cert-expiration
spec:
  version: "v1.0.0"
  homepage: https://github.com/marcocristofolini/kubectl-aks-cert-expiration
  shortDescription: Check AKS certificate expiration across all Azure subscriptions
  description: |
    This plugin checks the expiration of Kubernetes API server TLS certificates
    for AKS clusters across all subscriptions in an Azure account. It authenticates
    with Azure, iterates through each subscription, and checks the certificate
    expiration for all AKS clusters by connecting to the Kubernetes API server
    directly and inspecting the TLS certificate.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/marcocristofolini/kubectl-aks-cert-expiration/releases/download/v1.0.0/kubectl-aks_cert_expiration-linux-amd64.tar.gz
    sha256: b9f4610c9ee9ed231876119d3230604ea9537e4b3e79dd4b0cbcafe3a2d3014c
    files:
    - from: "kubectl-aks_cert_expiration"
      to: "."
    bin: "kubectl-aks_cert_expiration"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/marcocristofolini/kubectl-aks-cert-expiration/releases/download/v1.0.0/kubectl-aks_cert_expiration-darwin-amd64.tar.gz
    sha256: 2d6efa271cdc53538c9febfe039e11c0a88aa8f2a57a001c3f27ba4a54396370
    files:
    - from: "kubectl-aks_cert_expiration"
      to: "."
    bin: "kubectl-aks_cert_expiration"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/marcocristofolini/kubectl-aks-cert-expiration/releases/download/v1.0.0/kubectl-aks_cert_expiration-darwin-arm64.tar.gz
    sha256: df3681a7ec8c13bafdc4d94b8df3b632794b0e4fe4406aa8a819f0448571f6b8
    files:
    - from: "kubectl-aks_cert_expiration"
      to: "."
    bin: "kubectl-aks_cert_expiration"
